/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Splash;

/**
 *
 * @author jhpen
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barra = new javax.swing.JProgressBar();
        carga = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra.setForeground(new java.awt.Color(0, 153, 51));
        jPanel1.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 20));

        carga.setFont(new java.awt.Font("Agency FB", 3, 24)); // NOI18N
        carga.setForeground(new java.awt.Color(0, 0, 0));
        carga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(carga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 430, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       Splash sp=new Splash();
       sp.setVisible(true);
        try {
           for(int i=0; i<=100; i++){
           Thread.sleep(50);
           sp.barra.setValue(i);
           sp.carga.setText("Sistema esta cargando por favor espere ... "+(Integer.toString(i)+"%"));
           if(i==100){
           sp.setVisible(false);
           Vista.Terminos lg=new Vista.Terminos();
           lg.setVisible(true);
           }
           }  
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    private javax.swing.JLabel carga;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
