/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author jhpen
 */
public class Terminos extends javax.swing.JFrame {

    /**
     * Creates new form Terminos
     */
    public Terminos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        checkAceptar = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TERMINOS Y CONDICIONES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 280, 30));

        btnEntrar.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrar.setText("GET IN");
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        checkAceptar.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        checkAceptar.setText("ACEPTO TERMINOS Y CONDICIONES");
        jPanel1.add(checkAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("    \n    EL aplicativo que esta diseñao con la  proteccion de datos de la \n    Ley 1581 de 2012, \n    Al comprar un artículo, aceptas que: \n    (i) eres responsable de leer el listado completo del artículo \n    antes de comprometerte a comprarlo: \n    (ii) celebras un contrato legalmente vinculante para comprar\n    un artículo cuando te comprometed a comprar un artículo y \n    completar el proceso de check-out.\n    Cuando recibimos un reclamo de garantía válido de un producto\n    que vendemos, repararemos el defecto relevante o\n    reemplazaremos el producto. Si no podemos reparar \n    o reemplazar el producto dentro de un tiempo razonable,\n    el cliente tendrá derecho a un reembolso total cuando \n    nos devuelva el producto. Pagaremos el envío de los \n    productos reparados o reemplazados al cliente y\n    el cliente será responsable de devolvernos el \n    producto. El Servicio y todos los materiales\n    incluidos o transferidos,  incluyendo, sin limitación, \n     software, imágenes, texto,   gráficos, logotipos,\n    patentes, marcas registradas, marcas \n    de servicio, derechos de autor, fotografías, audio, \n    videos, música  y todos los Derechos de Propiedad \n    Intelectual relacionados con ellos, son la propiedad\n   exclusiva de [Nombre del propietario de la\n    página web]. Salvo que se indique explícitamente en\n   este documento, no se considerará que nada en estos\n   Términos  crea una licencia en o bajo ninguno de \n   dichos Derechos de Propiedad Intelectual, y tu aceptas\n  no vender, licenciar, alquilar,modificar, distribuir, copiar,\n reproducir, transmitir, exhibir públicamente, realizar \npúblicamente, publicar, adaptar, \n   editar o crear trabajos derivados de los mismos.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 370, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        // TODO add your handling code here:
         if (checkAceptar.isSelected()) {
            Loginv st = new Loginv();
            st.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "ERROR NO SELECCIONO LA OPCION");

        }                                      
    }//GEN-LAST:event_btnEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terminos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terminos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terminos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terminos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Terminos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JCheckBox checkAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
